### ISSUE TITLE
No module named 'fontParts'

### ISSUE THREAD

**Issue by jaymanu79** [smugpie/amiga-bitmap-font-tools#5]
Hello

I exactly followed your instructions and getting error : No module named 'fontParts'
Could you please help ?
Thanks
 
:/mnt/ramdisk/amiga-bitmap-font-tools/python$ python3 -m venv .
:/mnt/ramdisk/amiga-bitmap-font-tools/python$ source ./bin/activate
(python) :/mnt/ramdisk/amiga-bitmap-font-tools/python$ pip3 install fontparts fontmake
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: fontparts in /usr/local/lib/python3.10/dist-packages (0.11.0)
Requirement already satisfied: fontmake in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: FontTools[lxml,ufo,unicode]>=3.32.0 in /usr/local/lib/python3.10/dist-packages (from fontparts) (4.42.1)
Requirement already satisfied: fontMath>=0.4.8 in /usr/local/lib/python3.10/dist-packages (from fontparts) (0.9.3)
Requirement already satisfied: defcon[pens]>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from fontparts) (0.10.3)
Requirement already satisfied: booleanOperations>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from fontparts) (0.9.0)
Requirement already satisfied: attrs>=19 in /usr/local/lib/python3.10/dist-packages (from fontmake) (23.1.0)
Requirement already satisfied: ufo2ft[compreffor]>=2.33.4 in /usr/local/lib/python3.10/dist-packages (from fontmake) (2.33.4)
Requirement already satisfied: glyphsLib>=6.2.5 in /usr/local/lib/python3.10/dist-packages (from fontmake) (6.4.0)
Requirement already satisfied: ufoLib2>=0.16.0 in /usr/local/lib/python3.10/dist-packages (from fontmake) (0.16.0)
Requirement already satisfied: pyclipper>=1.1.0.post1 in /usr/local/lib/python3.10/dist-packages (from booleanOperations>=0.9.0->fontparts) (1.3.0.post5)
Requirement already satisfied: fontPens>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from defcon[pens]>=0.6.0->fontparts) (0.2.4)
Requirement already satisfied: fs<3,>=2.2.0 in /usr/lib/python3/dist-packages (from FontTools[lxml,ufo,unicode]>=3.32.0->fontparts) (2.4.12)
Requirement already satisfied: lxml<5,>=4.0 in /usr/lib/python3/dist-packages (from FontTools[lxml,ufo,unicode]>=3.32.0->fontparts) (4.8.0)
Requirement already satisfied: unicodedata2>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from FontTools[lxml,ufo,unicode]>=3.32.0->fontparts) (15.1.0)
Requirement already satisfied: openstep-plist>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from glyphsLib>=6.2.5->fontmake) (0.3.1)
Requirement already satisfied: cffsubr>=0.2.8 in /usr/local/lib/python3.10/dist-packages (from ufo2ft[compreffor]>=2.33.4->fontmake) (0.2.9.post1)
Requirement already satisfied: compreffor>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from ufo2ft[compreffor]>=2.33.4->fontmake) (0.5.5)
(python) jmj@jmj-yoga2:/mnt/ramdisk/amiga-bitmap-font-tools/python$ python ./openAmigaFont.py 
Traceback (most recent call last):
  File "/mnt/ramdisk/amiga-bitmap-font-tools/python/./openAmigaFont.py", line 9, in <module>
    from drawing import drawPixel
  File "/mnt/ramdisk/amiga-bitmap-font-tools/python/drawing.py", line 1, in <module>
    from fontParts.world import dispatcher
ModuleNotFoundError: No module named 'fontParts'

**Comment by jaymanu79** [comment]
it seems the right command is
python3 -m pip install fontparts fontmake

**Comment by gingerbeardman** [comment]
Even with `python3 -m pip install fontparts fontmake`

I'm getting the same error

```
❯ python ./openAmigaFont.py -i diamond.font -o diamond.otf -f otf
Traceback (most recent call last):
  File "/Users/matt/Downloads/2023-10-15/amiga-bitmap-font-tools-main/python/./openAmigaFont.py", line 9, in <module>
    from drawing import drawPixel
  File "/Users/matt/Downloads/2023-10-15/amiga-bitmap-font-tools-main/python/drawing.py", line 1, in <module>
    from fontParts.world import dispatcher
ModuleNotFoundError: No module named 'fontParts'
```

**Comment by smugpie** [comment]
Hello @jaymanu79 @gingerbeardman! Thanks for logging and contributing to this issue. So when I wrote the documentation for this, I was on a Mac running solely Python 3.10 I think. I hadn't anticipated the level of interest that this project has generated and didn't beef up the docs accordingly. I think your issues are different. I'll respond to each in separate comments if you don't mind.

**Comment by smugpie** [comment]
@jaymanu79 @gingerbeardman This applies to both of you. What versions of Python do you have available to you? What do you get if you just type `python -V` in a terminal? What about `python3 -V`?

**Comment by smugpie** [comment]
@gingerbeardman if you have a version 2 and a version 3 of Python installed, then just use `python3` everywhere. Don't use `python`. What happens if you then run `python3 ./openAmigaFont.py -i diamond.font -o diamond.otf -f otf`?

**Comment by smugpie** [comment]
@jaymanu79 what OS are you running? The pathname in the error message suggests you're running this in a ramdisk? There might be permissions errors on that disk preventing you from running it there maybe?

**Comment by gingerbeardman** [comment]
I'm macOS 12.7

```
% python -V
Python 3.11.5
```

**Comment by jaymanu79** [comment]
Hello
Thanks for your attention.

I'm on Ubuntu 22.04 
> python3 -V
Python 3.10.6

I tried your script on my home folder instead of ramdisk, and yes it worked like a charm !
Thanks for the work.

**Comment by smugpie** [comment]
> shall i close the issue ?

Glad all is working and thanks for letting me know! I shall close the issue once @gingerbeardman is sorted too.
